# Generated by Django 2.0.6 on 2019-08-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
    ]
